In [1]:
import numpy as np

In [2]:
#And operation
X=np.array([[0,0],[0,1],[1,0],[1,1]])
print(X)
Y=np.array([[0,1,1,0]]).T#different dimension of X and Y so taking transpose

print(Y)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[0]
 [1]
 [1]
 [0]]


In [3]:
def sig(z):
    return 1/(1+np.exp(-z))

In [4]:
def derivative_sig(z):
    return sig(z)*(1 - sig(z))

In [5]:
wh=2*np.random.random((2,2))-1
bh=2*np.random.random((1,2))-1
wo=2*np.random.random((2,1))-1

bo=2*np.random.random(1)-1
lr=0.1

In [6]:
for iter in range(100000):
    output0=X
    input_hidden=np.dot(output0,wh)+bh
    output_hidden=sig(input_hidden)
    inputForOutputLayer=np.dot(output_hidden,wo)+bo
    output=sig(inputForOutputLayer)
   
    
    first_term_output_layer=output-Y
    
    
    second_term_output_layer=derivative_sig(inputForOutputLayer)
    first_two_output_layer=first_term_output_layer*second_term_output_layer
    
    first_term_hidden_layer=np.dot(first_two_output_layer,wo.T)
    second_term_hidden_layer=derivative_sig(input_hidden)
    first_two_hidden_layer=first_term_hidden_layer*second_term_hidden_layer

    changes_output=np.dot(output_hidden.T,first_two_output_layer)
    changes_output_bias=np.sum(first_two_output_layer,axis=0,keepdims=True)

    changes_hidden=np.dot(output0.T,first_two_hidden_layer)
    changes_hidden_bias=np.sum(first_two_hidden_layer,axis=0,keepdims=True)

    wo=wo - lr*changes_output
    bo=bo-lr*changes_output_bias
    wh=wh-lr*changes_hidden
    bh=bh-lr*changes_hidden_bias


print(output)


print(wo,bo,wh,bh)


[[0.01503691]
 [0.98310717]
 [0.98304381]
 [0.01364241]]
[[-9.11340266]
 [-9.07453758]] [[13.45237081]] [[-6.70009966  7.20026056]
 [ 6.91567    -7.0137809 ]] [[3.38017099 3.54975111]]
